name: Build for macOS 12 (Intel) and macOS 13 (Apple Silicon)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runs-on: []
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pyenv
        run: |
          brew install pyenv
          echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
          eval "$(pyenv init --path)"
      - name: Set up Python 3.11.7
        run: pyenv install 3.11.7
      - name: Install Dependencies
        run: |
          cd standalone_app
          pyenv local 3.11.7
          pip install -U https://github.com/huggingface/transformers/archive/refs/heads/main.zip
          pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu -U
          pip install -r requirements.txt
      - name: Build standalone app
        run: |
          cd standalone_app
          pyenv local 3.11.7
          pyinstaller Snap2LaTeX.spec
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Snap2LaTeX.app
          path: standalone_app/dist/Snap2LaTeX.app
